<?php

return [
    [
        'group_key' => 'gl_core',
        'group_title' => 'บัญชีและภาษี / GL & Tax Core',
        'items' => [
            [
                'key' => 'gl_accounts',
                'title' => 'ผังบัญชี / Chart of Accounts',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_account',
            ],
            [
                'key' => 'gl_journal',
                'title' => 'สมุดรายวัน / Journal',
                'form_id' => 22,
                'mode' => 'master_detail',
                'main_table' => 'gl_journal',
                'detail_table' => 'gl_journal_line',
                'detail_source_column' => 'id',
                'detail_target_column' => 'journal_id',
                'main_doc_column' => 'journal_no',
                'process_enabled' => false,
            ],
            [
                'key' => 'gl_vat_tx',
                'title' => 'ภาษีมูลค่าเพิ่ม / VAT Transactions',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_vat_transaction',
            ],
            [
                'key' => 'gl_withholding_tx',
                'title' => 'ภาษีหัก ณ ที่จ่าย / Withholding Tax (WHT)',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_withholding_transaction',
            ],
        ],
    ],
    [
        'group_key' => 'gl_reports',
        'group_title' => 'รายงานบัญชีและภาษี / GL & Tax Reports',
        'items' => [
            [
                'key' => 'gl_trial_balance_report',
                'title' => 'รายงานงบทดลอง / Trial Balance',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_journal_line',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=gl_trial_balance',
            ],
            [
                'key' => 'gl_ledger_report',
                'title' => 'รายงานบัญชีแยกประเภท / General Ledger',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_journal_line',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=gl_ledger',
            ],
            [
                'key' => 'gl_tax_report',
                'title' => 'รายงานภาษีรายเดือน / VAT-WHT Summary',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_vat_transaction',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=gl_tax_summary',
            ],
            [
                'key' => 'gl_balance_sheet_report',
                'title' => 'งบดุล / Balance Sheet Report',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'gl_account',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=gl_balance_sheet',
            ],
        ],
    ],
    [
        'group_key' => 'hr_core',
        'group_title' => 'ทรัพยากรบุคคล / HR Core',
        'items' => [
            [
                'key' => 'hr_employee',
                'title' => 'พนักงาน / Employees',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_employee',
            ],
            [
                'key' => 'hr_attendance',
                'title' => 'เวลาเข้าออก ขาด ลา มาสาย OT / Attendance & OT',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_attendance',
            ],
            [
                'key' => 'hr_leave_type',
                'title' => 'ประเภทการลา / Leave Types',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_leave_type',
            ],
            [
                'key' => 'hr_leave_request',
                'title' => 'คำขอลางาน / Leave Requests',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_leave_request',
            ],
            [
                'key' => 'hr_payroll_period',
                'title' => 'รอบเงินเดือน / Payroll Periods',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_payroll_period',
            ],
            [
                'key' => 'hr_policy',
                'title' => 'นโยบายคำนวณตามกฎหมาย / Legal Payroll Policy',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_policy',
            ],
            [
                'key' => 'hr_payroll_line',
                'title' => 'ผลคำนวณเงินเดือน / Payroll Lines',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_payroll_line',
                'read_only' => true,
            ],
        ],
    ],
    [
        'group_key' => 'hr_reports',
        'group_title' => 'รายงานบุคคล / HR Reports',
        'items' => [
            [
                'key' => 'hr_attendance_report',
                'title' => 'รายงานสรุปเวลาเข้าออกงาน / Attendance Summary',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_attendance',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=hr_attendance',
            ],
            [
                'key' => 'hr_leave_report',
                'title' => 'รายงานสรุปการลา / Leave Summary',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_leave_request',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=hr_leave',
            ],
            [
                'key' => 'hr_payroll_report',
                'title' => 'รายงานสรุปเงินเดือน / Payroll Summary',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'hr_payroll_line',
                'read_only' => true,
                'custom_report_url' => 'business_report.php?report=hr_payroll',
            ],
        ],
    ],
];
