<?php

return [
    [
        'group_key' => 'inventory',
        'group_title' => 'รายละเอียดสินค้า',
        'items' => [
            [
                'key' => 'product_detail',
                'title' => 'รายละเอียดสินค้า',
                'form_id' => 1,
                'mode' => 'single',
                'main_table' => 'product',
            ],
            [
                'key' => 'adjust_stock',
                'title' => 'ปรับยอดสินค้า',
                'form_id' => 2,
                'mode' => 'single',
                'main_table' => 'stockcard',
            ],
            [
                'key' => 'adjust_price',
                'title' => 'ปรับราคาสินค้า',
                'form_id' => 3,
                'mode' => 'single',
                'main_table' => 'product_unit_price',
            ],
            [
                'key' => 'stock_card',
                'title' => 'สต๊อกการ์ด',
                'form_id' => 4,
                'mode' => 'single',
                'main_table' => 'stockcard',
            ],
            [
                'key' => 'transfer_stock',
                'title' => 'โอนสินค้าระหว่างคลัง',
                'form_id' => 5,
                'mode' => 'single',
                'main_table' => 'erp_stock_transfer',
            ],
            [
                'key' => 'warehouse_master',
                'title' => 'Warehouse Master',
                'form_id' => 5,
                'mode' => 'single',
                'main_table' => 'erp_warehouse',
            ],
            [
                'key' => 'warehouse_location',
                'title' => 'Warehouse Location',
                'form_id' => 5,
                'mode' => 'single',
                'main_table' => 'erp_warehouse_location',
            ],
            [
                'key' => 'warehouse_shelf',
                'title' => 'Warehouse Shelf',
                'form_id' => 5,
                'mode' => 'single',
                'main_table' => 'erp_warehouse_shelf',
            ],
            [
                'key' => 'create_project',
                'title' => 'สร้างโครงการบาร์โค้ด',
                'form_id' => 29,
                'mode' => 'single',
                'main_table' => 'product',
            ],
            [
                'key' => 'print_barcode',
                'title' => 'พิมพ์บาร์โค้ด',
                'form_id' => 30,
                'mode' => 'single',
                'main_table' => 'product',
            ],
        ],
    ],
    [
        'group_key' => 'creditor',
        'group_title' => 'เจ้าหนี้',
        'items' => [
            [
                'key' => 'creditor_detail',
                'title' => 'รายละเอียดเจ้าหนี้',
                'form_id' => 6,
                'mode' => 'single',
                'main_table' => 'creditor_detail',
            ],
            [
                'key' => 'creditor_billing',
                'title' => 'วางบิล',
                'form_id' => 7,
                'mode' => 'master_detail',
                'main_table' => 'creditor_billing',
                'detail_table' => 'creditor_billing_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_id',
                'bill_name' => 'creditorbilling',
                'main_doc_column' => 'bill_id',
            ],
            [
                'key' => 'creditor_paid',
                'title' => 'ชำระเงิน',
                'form_id' => 8,
                'mode' => 'master_detail',
                'main_table' => 'creditor_paid',
                'detail_table' => 'creditor_paid_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_id',
                'bill_name' => 'creditorpaid',
                'main_doc_column' => 'bill_id',
            ],
            [
                'key' => 'creditor_outstanding',
                'title' => 'เจ้าหนี้คงค้าง',
                'form_id' => 9,
                'mode' => 'placeholder',
                'message' => 'เมนูนี้ในระบบเดิมไม่มี handler ใน source ปัจจุบัน',
            ],
        ],
    ],
    [
        'group_key' => 'debtor',
        'group_title' => 'ลูกหนี้',
        'items' => [
            [
                'key' => 'deptor_detail',
                'title' => 'รายละเอียดลูกหนี้',
                'form_id' => 10,
                'mode' => 'single',
                'main_table' => 'deptor',
            ],
            [
                'key' => 'deptor_billing',
                'title' => 'วางบิล',
                'form_id' => 11,
                'mode' => 'master_detail',
                'main_table' => 'deptor_billing',
                'detail_table' => 'deptor_billing_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_id',
                'bill_name' => 'debtorbilling',
                'main_doc_column' => 'bill_id',
            ],
            [
                'key' => 'deptor_paid',
                'title' => 'รับชำระเงิน',
                'form_id' => 12,
                'mode' => 'master_detail',
                'main_table' => 'deptor_payment',
                'detail_table' => 'deptor_paid_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_id',
                'bill_name' => 'debtorpaid',
                'main_doc_column' => 'bill_id',
            ],
            [
                'key' => 'deptor_billing_control',
                'title' => 'ใบคุมวางบิล',
                'form_id' => 11,
                'mode' => 'single',
                'main_table' => 'deptor_billing_detail',
            ],
        ],
    ],
    [
        'group_key' => 'buy',
        'group_title' => 'ซื้อ',
        'items' => [
            [
                'key' => 'buy_cash',
                'title' => 'ซื้อสด',
                'form_id' => 14,
                'mode' => 'master_detail',
                'main_table' => 'bill_buy',
                'detail_table' => 'bill_buy_detail',
                'detail_source_column' => 'bill_buy_id',
                'detail_target_column' => 'bill_buy_id',
                'bill_name' => 'buycash',
                'main_doc_column' => 'bill_buy_id',
                'detail_qty_column' => 'recive_item',
                'detail_price_column' => 'items_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'buy_credit',
                'title' => 'ซื้อเชื่อ',
                'form_id' => 15,
                'mode' => 'master_detail',
                'main_table' => 'bill_buy_credit',
                'detail_table' => 'bill_buy_credit_detail',
                'detail_source_column' => 'bill_buy_id',
                'detail_target_column' => 'bill_buy_id',
                'bill_name' => 'buycredit',
                'main_doc_column' => 'bill_buy_id',
                'detail_qty_column' => 'recive_item',
                'detail_price_column' => 'items_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'buy_sendback',
                'title' => 'ส่งคืน',
                'form_id' => 16,
                'mode' => 'master_detail',
                'main_table' => 'buy_return',
                'detail_table' => 'buy_return_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'br_bill_id',
                'bill_name' => 'buysendback',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'items',
                'detail_price_column' => 'unit_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'buy_order',
                'title' => 'สั่งซื้อ',
                'form_id' => 17,
                'mode' => 'master_detail',
                'main_table' => 'bill_buy_order',
                'detail_table' => 'bill_buy_order_detail',
                'detail_source_column' => 'bill_buy_id',
                'detail_target_column' => 'bill_buy_id',
                'bill_name' => 'buyorder',
                'main_doc_column' => 'bill_buy_id',
                'detail_qty_column' => 'recive_item',
                'detail_price_column' => 'items_price',
                'detail_amount_column' => 'amount',
            ],
        ],
    ],
    [
        'group_key' => 'sale',
        'group_title' => 'ขาย',
        'items' => [
            [
                'key' => 'sale_cash',
                'title' => 'ขายสด',
                'form_id' => 18,
                'mode' => 'master_detail',
                'main_table' => 'bill_salecash',
                'detail_table' => 'bill_salecash_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_salecash_id',
                'bill_name' => 'salecash',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'delivery_items',
                'detail_price_column' => 'item_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'sale_credit',
                'title' => 'ขายเชื่อ',
                'form_id' => 19,
                'mode' => 'master_detail',
                'main_table' => 'bill_salecredit',
                'detail_table' => 'bill_salecredit_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_salecredit_id',
                'bill_name' => 'salecredit',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'delivery_items',
                'detail_price_column' => 'item_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'sale_return',
                'title' => 'รับคืน',
                'form_id' => 20,
                'mode' => 'master_detail',
                'main_table' => 'sale_return',
                'detail_table' => 'sale_return_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'br_bill_id',
                'bill_name' => 'salereturn',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'items',
                'detail_price_column' => 'unit_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'quotation',
                'title' => 'ใบเสนอราคา',
                'form_id' => 21,
                'mode' => 'master_detail',
                'main_table' => 'quatation',
                'detail_table' => 'quatation_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_salecash_id',
                'bill_name' => 'quatation',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'delivery_items',
                'detail_price_column' => 'item_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'booking',
                'title' => 'ใบจอง',
                'form_id' => 22,
                'mode' => 'master_detail',
                'main_table' => 'bill_booking',
                'detail_table' => 'bill_booking_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_booking_id',
                'bill_name' => 'booking',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'delivery_items',
                'detail_price_column' => 'item_price',
                'detail_amount_column' => 'amount',
            ],
            [
                'key' => 'client_receive',
                'title' => 'รับสินค้าลูกค้า',
                'form_id' => 21,
                'mode' => 'master_detail',
                'main_table' => 'clientrecive',
                'detail_table' => 'clientrecive_detail',
                'detail_source_column' => 'bill_id',
                'detail_target_column' => 'bill_salecash_id',
                'bill_name' => 'clientrecive',
                'main_doc_column' => 'bill_id',
                'detail_qty_column' => 'delivery_items',
                'detail_price_column' => 'item_price',
                'detail_amount_column' => 'amount',
            ],
        ],
    ],
    [
        'group_key' => 'report',
        'group_title' => 'รายงาน',
        'items' => [
            [
                'key' => 'report_buy',
                'title' => 'รายงานซื้อ',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'bill_buy',
            ],
            [
                'key' => 'report_sale',
                'title' => 'รายงานขาย',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'bill_salecash',
            ],
            [
                'key' => 'report_product_balance',
                'title' => 'สินค้าคงเหลือ',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'product',
            ],
            [
                'key' => 'report_log',
                'title' => 'รายงานบันทึกระบบ / Log Report',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'act_log',
            ],
            [
                'key' => 'report_product_activity',
                'title' => 'รายงานความเคลื่อนไหวสินค้า',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'stockcard',
            ],
            [
                'key' => 'report_deptor_payment',
                'title' => 'รายงานรับชำระ',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'deptor_payment',
            ],
        ],
    ],
    [
        'group_key' => 'setup',
        'group_title' => 'ตั้งค่า',
        'items' => [
            [
                'key' => 'setup_bill',
                'title' => 'ตั้งค่า bill',
                'form_id' => 25,
                'mode' => 'single',
                'main_table' => 'billid',
            ],
            [
                'key' => 'setup_user',
                'title' => 'ตั้งค่าผู้ใช้',
                'form_id' => 26,
                'mode' => 'single',
                'main_table' => 'unpw',
            ],
            [
                'key' => 'setup_sale_person',
                'title' => 'พนักงานขาย',
                'form_id' => 25,
                'mode' => 'single',
                'main_table' => 'unpw',
            ],
            [
                'key' => 'setup_server',
                'title' => 'ตั้งค่าเซิร์ฟเวอร์ / Setup Server',
                'form_id' => 25,
                'mode' => 'single',
                'main_table' => 'company',
            ],
        ],
    ],
];
