<?php

return [
    [
        'group_key' => 'mfg_engineering',
        'group_title' => 'วิศวกรรมการผลิต / MFG Engineering',
        'items' => [
            [
                'key' => 'mfg_item_master',
                'title' => 'ข้อมูลสินค้าเพื่อการผลิต / Item Master (MFG)',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_item',
            ],
            [
                'key' => 'mfg_bom_header',
                'title' => 'หัว BOM (แยกเวอร์ชัน) / BOM Header (Versioned)',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_bom_header',
            ],
            [
                'key' => 'mfg_bom_line',
                'title' => 'รายการ BOM / BOM Lines',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_bom_line',
            ],
            [
                'key' => 'mfg_routing_header',
                'title' => 'หัวเส้นทางการผลิต (แยกเวอร์ชัน) / Routing Header (Versioned)',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_routing_header',
            ],
            [
                'key' => 'mfg_routing_step',
                'title' => 'ขั้นตอนการผลิต / Routing Steps',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_routing_step',
            ],
            [
                'key' => 'mfg_work_center',
                'title' => 'ศูนย์งาน / Work Centers',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_work_center',
            ],
            [
                'key' => 'mfg_work_center_alt',
                'title' => 'ศูนย์งานทางเลือก / Alternative Work Centers',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_work_center_alt',
            ],
            [
                'key' => 'mfg_center_calendar',
                'title' => 'ปฏิทินศูนย์งาน / Work Center Calendar',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_work_center_calendar',
            ],
            [
                'key' => 'mfg_setup_matrix',
                'title' => 'เมทริกซ์การตั้งเครื่อง (เปลี่ยนงาน) / Setup Matrix (Changeover)',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_setup_matrix',
            ],
            [
                'key' => 'mfg_center_shift',
                'title' => 'กะการทำงานศูนย์งาน / Work Center Shifts',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_work_center_shift',
            ],
        ],
    ],
    [
        'group_key' => 'mfg_planning',
        'group_title' => 'วางแผนการผลิต (APS) / MFG Planning (APS)',
        'items' => [
            [
                'key' => 'mfg_production_order',
                'title' => 'ใบสั่งผลิต / Production Orders',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_production_order',
            ],
            [
                'key' => 'mfg_aps_schedule',
                'title' => 'กระดานตาราง APS / APS Schedule Board',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_aps_schedule',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=aps_board',
            ],
            [
                'key' => 'mfg_supply_policy',
                'title' => 'นโยบายอุปทาน (ROP/JIT) / Supply Policy (ROP/JIT)',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'supply_item_policy',
            ],
            [
                'key' => 'mfg_forecast',
                'title' => 'พยากรณ์ความต้องการ / Demand Forecast',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'demand_forecast',
            ],
            [
                'key' => 'mfg_material_reservation',
                'title' => 'จองวัตถุดิบ / Material Reservation',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_material_reservation',
            ],
            [
                'key' => 'mfg_purchase_req',
                'title' => 'ใบขอซื้อ / Purchase Requisition',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'purchase_requisition',
            ],
            [
                'key' => 'mfg_inventory_snapshot',
                'title' => 'ภาพรวมสินค้าคงคลัง / Inventory Snapshot',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_inventory_snapshot',
            ],
        ],
    ],
    [
        'group_key' => 'mfg_shopfloor',
        'group_title' => 'หน้างานผลิตและ IoT / MFG Shop Floor & IoT',
        'items' => [
            [
                'key' => 'mfg_iot_device',
                'title' => 'อุปกรณ์ IoT / IoT Devices',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'iot_device',
            ],
            [
                'key' => 'mfg_iot_log',
                'title' => 'บันทึกเซนเซอร์ IoT / IoT Sensor Logs',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'iot_sensor_log',
                'read_only' => true,
            ],
            [
                'key' => 'mfg_job_sheet',
                'title' => 'ใบงานดิจิทัล / Digital Job Sheets',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_digital_job_sheet',
            ],
            [
                'key' => 'mfg_lot',
                'title' => 'ล็อตการผลิต / Production Lots',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_lot',
            ],
            [
                'key' => 'mfg_lot_consumption',
                'title' => 'การใช้ล็อต / Lot Consumption',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_lot_consumption',
            ],
            [
                'key' => 'mfg_lot_dispatch',
                'title' => 'จ่ายออกล็อต / Lot Dispatch',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_lot_dispatch',
            ],
        ],
    ],
    [
        'group_key' => 'mfg_quality',
        'group_title' => 'คุณภาพการผลิต (QMS) / MFG Quality (QMS)',
        'items' => [
            [
                'key' => 'mfg_qms_plan',
                'title' => 'แผนการตรวจสอบ / Inspection Plans',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'qms_inspection_plan',
            ],
            [
                'key' => 'mfg_qms_result',
                'title' => 'ผลการตรวจสอบ / Inspection Results',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'qms_inspection_result',
            ],
        ],
    ],
    [
        'group_key' => 'mfg_maintenance',
        'group_title' => 'ซ่อมบำรุงการผลิต / MFG Maintenance',
        'items' => [
            [
                'key' => 'mfg_asset_machine',
                'title' => 'เครื่องจักรและสินทรัพย์ / Machines & Assets',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'asset_machine',
            ],
            [
                'key' => 'mfg_runtime_log',
                'title' => 'บันทึกเวลาทำงาน / Runtime Logs',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'machine_runtime_log',
            ],
            [
                'key' => 'mfg_maintenance_plan',
                'title' => 'แผนซ่อมบำรุง / Maintenance Plans',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'maintenance_plan',
            ],
            [
                'key' => 'mfg_maintenance_wo',
                'title' => 'ใบงานซ่อมบำรุง / Maintenance Work Orders',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'maintenance_work_order',
            ],
        ],
    ],
    [
        'group_key' => 'mfg_reports',
        'group_title' => 'รายงานการผลิต / MFG Reports',
        'items' => [
            [
                'key' => 'mfg_dashboard',
                'title' => 'แดชบอร์ดเรียลไทม์ / Realtime Dashboard',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_aps_schedule',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_dashboard.php',
            ],
            [
                'key' => 'mfg_report_bom_explosion',
                'title' => 'รายละเอียดโครงสร้างผลิตภัณฑ์ BOM / Product BOM Structure Details',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_bom_header',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=bom_explosion',
            ],
            [
                'key' => 'mfg_report_routing_plan',
                'title' => 'เส้นทางผลิตและศูนย์งานทางเลือก / Routing & Alternative WC',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_routing_step',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=routing_plan',
            ],
            [
                'key' => 'mfg_report_resource_utilization',
                'title' => 'การใช้ทรัพยากร / Resource Utilization',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_aps_schedule',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=resource_utilization',
            ],
            [
                'key' => 'mfg_report_trace_backward',
                'title' => 'ติดตามย้อนหลัง / Traceability Backward',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_lot_consumption',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=trace_backward',
            ],
            [
                'key' => 'mfg_report_trace_forward',
                'title' => 'ติดตามไปข้างหน้า / Traceability Forward',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_lot_dispatch',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=trace_forward',
            ],
            [
                'key' => 'mfg_report_spc',
                'title' => 'รายงานควบคุม SPC / SPC Control Report',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'qms_inspection_result',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=spc',
            ],
            [
                'key' => 'mfg_report_maintenance_due',
                'title' => 'ครบกำหนดซ่อมบำรุงเชิงป้องกัน / Preventive Maintenance Due',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'maintenance_plan',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=maintenance_due',
            ],
            [
                'key' => 'mfg_report_maintenance_risk',
                'title' => 'ความเสี่ยงซ่อมบำรุงเชิงคาดการณ์ / Predictive Maintenance Risk',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'machine_runtime_log',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=maintenance_risk',
            ],
            [
                'key' => 'mfg_report_inventory_reorder',
                'title' => 'จุดสั่งซื้ออัตโนมัติ / Auto Reorder Point',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'supply_item_policy',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=inventory_reorder',
            ],
            [
                'key' => 'mfg_report_jit_plan',
                'title' => 'แผน JIT / JIT Plan',
                'form_id' => 22,
                'mode' => 'single',
                'main_table' => 'mfg_material_reservation',
                'read_only' => true,
                'custom_report_url' => 'manufacturing_report.php?report=jit_plan',
            ],
        ],
    ],
];
